import jsPDF from "jspdf";
import Button from "./ui/Button";
import { FileText, Printer } from "lucide-react";

function ReportGenerator({ alerts }) {
  const generatePDF = () => {
    const doc = new jsPDF();

    const totalAlerts = alerts.length;
    const high = alerts.filter((a) => a.threat === "High").length;
    const medium = alerts.filter((a) => a.threat === "Medium").length;
    const low = alerts.filter((a) => a.threat === "Low").length;

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(0, 229, 255); // Nexora Cyan
    doc.text("Nexora Security Report", 20, 20);

    doc.setDrawColor(0, 229, 255);
    doc.line(20, 25, 190, 25);

    // Report Info
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);

    doc.text(`Generated On : ${new Date().toLocaleString()}`, 20, 40);
    doc.text("System Status : Monitoring", 20, 50);

    // Summary Box
    doc.roundedRect(20, 60, 170, 60, 3, 3);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text("Security Summary", 25, 73);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    doc.text(`Total Alerts : ${totalAlerts}`, 30, 87);
    doc.text(`High Threats : ${high}`, 30, 97);
    doc.text(`Medium Threats : ${medium}`, 30, 107);
    doc.text(`Low Threats : ${low}`, 30, 117);

    // Recent Alerts
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Recent Alerts", 20, 140);

    let y = 152;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    alerts.slice(0, 10).forEach((alert) => {
      doc.text(
        `${alert.time} | ${alert.file} | ${alert.status} | ${alert.threat}`,
        20,
        y,
      );

      y += 10;

      if (y > 270) {
        doc.addPage();
        y = 20;
      }
    });

    // Footer
    doc.setDrawColor(180);
    doc.line(20, 280, 190, 280);

    doc.setFontSize(10);
    doc.setTextColor(100);

    doc.text(
      "Generated by Nexora AI - File Integrity Monitoring System",
      20,
      287,
    );

    doc.save("Nexora_Security_Report.pdf");
  };

  return (
    <div
      style={{
        display: "flex",
        gap: "1rem",
        justifyContent: "flex-end",
      }}
    >
      <Button
        variant="primary"
        onClick={generatePDF}
        icon={FileText}
      >
        Download PDF
      </Button>

      <Button
        variant="secondary"
        onClick={() => window.print()}
        icon={Printer}
      >
        Print Report
      </Button>
    </div>
  );
}

export default ReportGenerator;
